name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "master" ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          SPRING_CONFIG_LOCATION: src/test/resources/application-test.yml
        run: mvn package --file pom.xml
      - name: Run Unit Tests
        env:
          SPRING_CONFIG_LOCATION: src/test/resources/application-test.yml
        run: mvn test --file pom.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker build . --tag brewery-tour-rest-api:$GITHUB_SHA --build-arg DB_URL=$DB_URL --build-arg DB_USER=$DB_USER --build-arg DB_PASSWORD=$DB_PASSWORD

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to Fly.io
        run: |
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Create Fly app
        if: ${{ !success() }}
        run: |
          flyctl apps create brewery-tour-rest-api

      - name: Initial deploy
        run: |
          flyctl deploy --image brewery-tour-rest-api:$GITHUB_SHA -a brewery-tour-rest-api  --strategy native

      - name: Subsequent deploy
        run: |
          flyctl deploy --image brewery-tour-rest-api:$GITHUB_SHA -a brewery-tour-rest-api

      - name: Verify deployment
        run: |
          flyctl auth whoami
          flyctl apps list
          flyctl status